# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Qanawat DCB DEV(ee09fb3f-1b3f-4bf2-85e4-2d3b593df783)'
    appType: 'webAppLinux'
    appName: '2n-webapp'
    deployToSlotOrASE: true
    resourceGroupName: 'aspmvc-app_group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|6.0'